version: '3.4'

services:
  web1:
    image: oms
    build:
      context: .
      dockerfile: OMS/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - SqlServerDb
      - InventoryServ
      - PaymentServ
      - RabbitMqServer
  InventoryServ:
    image: inventoryservice
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - "5002:8080"
      - "5003:8081"
    depends_on:
      - RabbitMqServer

  PaymentServ:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "5004:8080"
      - "5005:8081"
    depends_on:
      - RabbitMqServer
  SqlServerDb:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  RabbitMqServer:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 5







